<a href="https://colab.research.google.com/github/sprince0031/ICT-Python-ML/blob/main/Week%203/Notebooks/Week3_solutions.ipynb" target="_blank"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python & ML Foundations: Session 3 Solutions
## NumPy & Pandas

Welcome to the session 3 tutorial and companion notebook! This week, we'll learn to do basic mathematical operations of n-dimensional arrays using NumPy and pre-process a real-world housing dataset that's available in colab's sample folder.

## Utility code
The below code cell contains any common imports or sample data that can be useful for your exercises. Make sure to run this cell first before starting your exercises!

In [ ]:
import pandas as pd
import numpy as np

---
# Video Challenges

## 1. NumPy

This assignment tests your ability to use NumPy to prepare a dataset for a machine learning task. Use `np.random.seed(42)` to ensure your results are reproducible.

### Create a Dataset
Create a 10x4 NumPy array representing 10 houses with the following columns:
* **Square Footage:** Random integers from `1000` to `3000`
* **Bedrooms:** Random integers from `2` to `6`
* **House Age:** Random integers from `1` to `50`
* **House Price:** Random floats from `150.0` to `750.0`

Print the resulting array

### Filter the Data
Using boolean indexing, create a new array containing only the houses with more than 3 bedrooms and an age of less than 20 years.

Print the filtered array and its `.shape`.


In [ ]:
# Your code here

# Create numpy 10x1 arrays for each of the columns
sq_footage = np.random.randint(1000, 3001, size = (10,1))
bedrooms = np.random.randint(2,7, size = (10,1))
house_age = np.random.randint(1,51, size = (10,1))
house_price = np.random.uniform(150.0, 750.1, size=(10,1))

# Colate the arrays into a single 10x4 array
house_data = np.hstack((sq_footage, bedrooms, house_age, house_price))

print(f'Full house data:\n{house_data}')

Full house data:
[[2.42100000e+03 6.00000000e+00 2.50000000e+01 6.70593588e+02]
 [1.42900000e+03 6.00000000e+00 2.60000000e+01 5.50809405e+02]
 [2.19100000e+03 2.00000000e+00 2.50000000e+01 6.51333297e+02]
 [2.02900000e+03 5.00000000e+00 3.90000000e+01 6.92507376e+02]
 [1.20600000e+03 6.00000000e+00 5.00000000e+01 6.76587177e+02]
 [2.14400000e+03 6.00000000e+00 2.40000000e+01 5.97477488e+02]
 [2.28500000e+03 4.00000000e+00 2.10000000e+01 3.64776175e+02]
 [1.32700000e+03 4.00000000e+00 1.80000000e+01 6.53777287e+02]
 [2.43200000e+03 6.00000000e+00 3.80000000e+01 4.37571048e+02]
 [1.72200000e+03 3.00000000e+00 3.80000000e+01 3.20958615e+02]]


In [ ]:
# Filter data
more_than_3_bedrooms = house_data[:,1] > 3
age_less_than_20 = house_data[:,2] < 20

combined_filter = more_than_3_bedrooms & age_less_than_20

filtered_houses = house_data[combined_filter]

# Print filtered numpy array and its shape
print(f'Filtered house data:\n{filtered_houses}')
print(f'Shape of filtered data: {filtered_houses.shape}')

Filtered house data:
[[1327.            4.           18.          653.77728692]]
Shape of filtered data: (1, 4)


## 2. Pandas

**Run the Data Corruption Code:**

It will load the test dataset and introduce several common data quality issues.

In [ ]:
# --- RUN THIS CODE FIRST ---
# This code will create a corrupted DataFrame for you to fix.

# Load the test dataset
test_path = '/content/sample_data/california_housing_test.csv'
df_challenge = pd.read_csv(test_path)

# Introduce NaN values
df_challenge.loc[[5, 20, 50], 'total_rooms'] = np.nan
df_challenge.loc[[10, 30, 60], 'population'] = np.nan

# Introduce extreme outliers
df_challenge.loc[[100, 200], 'housing_median_age'] = 999

# Introduce incorrect data type
df_challenge['households'] = df_challenge['households'].astype(str)

print("--- Corrupted Dataset is Ready ---")
df_challenge.info()

--- Corrupted Dataset is Ready ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         2997 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          2997 non-null   float64
 6   households          3000 non-null   object 
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(8), object(1)
memory usage: 211.1+ KB


**Clean the Data**

Now, write the code to fix the `df_challenge` DataFrame.

 * **Inspect the Damage:** After running the code above, use `.info()` and `.describe()` to identify all the problems that were introduced.

 * **Fix Data Types:**  The households column was incorrectly converted to an object (string). Convert it back to a numeric type. Hint: Use `pd.to_numeric()`

 * **Handle Missing Values:** Fill the `Nan` values in `total_rooms` and population with their respective means.

 * **Handle Outliers:** The `housing_median_age` column now has unrealistic values. Filter the DataFrame to remove any rows where `housing_median_age` is greater than `90`.

 Print the `.info()` and `.describe()` outputs of your final, cleaned DataFrame to prove that all the issues have been resolved.

In [ ]:
# Finding data types of all columns
df_challenge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         2997 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          2997 non-null   float64
 6   households          3000 non-null   object 
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(8), object(1)
memory usage: 211.1+ KB


In [ ]:
# Finding counts and stats of columns
df_challenge.describe()

longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   2997.000000   
mean   -119.589200    35.63539           29.486667   2598.072739   
std       1.994936     2.12967           28.013605   2152.303847   
min    -124.180000    32.56000            1.000000      6.000000   
25%    -121.810000    33.93000           18.000000   1401.000000   
50%    -118.485000    34.27000           29.000000   2107.000000   
75%    -118.020000    37.69000           37.000000   3128.000000   
max    -114.490000    41.92000          999.000000  30450.000000   

       total_bedrooms    population  median_income  median_house_value  
count     3000.000000   2997.000000    3000.000000          3000.00000  
mean       529.950667   1403.435102       3.807272        205846.27500  
std        415.654368   1030.795191       1.854512        113119.68747  
min          2.000000      5.000000       0.499900         22500.00000  
25%        291.000000    780.000000       2.544000        121200.00000  
50%        437.000000   1155.000000       3.487150        177650.00000  
75%        636.000000   1745.000000       4.656475        263975.00000  
max       5419.000000  11935.000000      15.000100        500001.00000

In [ ]:
# Fixing incorrect datatype of `object`(string) to `float`
df_challenge['households'] = df_challenge['households'].astype(float)

# Verifying the datatype change
df_challenge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         2997 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          2997 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [ ]:
# Plugging missing values with mean of respective columns
total_rooms_mean = df_challenge['total_rooms'].mean()
population_mean = df_challenge['population'].mean()

df_challenge.fillna({'total_rooms': total_rooms_mean, 'population': population_mean}, inplace = True)

# Verifying that the values have been filled
df_challenge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


In [ ]:
# Checking for outliers in `housing_median_age` i.e., >= 90 years of age which would be rare and implausible
display(df_challenge[df_challenge['housing_median_age']>=90])

# Filtering out the outliers
df_filtered = df_challenge[df_challenge['housing_median_age'] < 90]

df_filtered.info()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
100    -118.30     34.02               999.0       2120.0           483.0   
200    -123.28     40.77               999.0        767.0           206.0   

     population  households  median_income  median_house_value  
100      1522.0       416.0          1.850            116800.0  
200       301.0       121.0          1.625             79200.0

<class 'pandas.core.frame.DataFrame'>
Index: 2998 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           2998 non-null   float64
 1   latitude            2998 non-null   float64
 2   housing_median_age  2998 non-null   float64
 3   total_rooms         2998 non-null   float64
 4   total_bedrooms      2998 non-null   float64
 5   population          2998 non-null   float64
 6   households          2998 non-null   float64
 7   median_income       2998 non-null   float64
 8   median_house_value  2998 non-null   float64
dtypes: float64(9)
memory usage: 234.2 KB


In [ ]:
# Verifying the outliers have been removed
print(df_filtered[df_filtered['housing_median_age']>=90])

Empty DataFrame
Columns: [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, median_house_value]
Index: []


---
# Practice Challenges

## Video Game Sales Analysis

This exercise will guide you through a basic data analysis project to practice your data loading, cleaning, and exploration skills using pandas for data manipulation and numpy for numerical calculations.

 We will be using the Video Game Sales dataset from Kaggle.
 * You can download it here: https://www.kaggle.com/datasets/gregorut/videogamesales


### Step 1: Setup and Data Loading

 Make sure you have uploaded the `vgsales.csv` file to your Colab environment.

* Load the `vgsales.csv` file into a pandas DataFrame named df.
* Display the first 5 rows of the DataFrame using `df.head()` to ensure it's loaded correctly.


In [ ]:
file_path = 'vgsales.csv'
df = pd.read_csv(file_path)

# Display the first few rows
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:


Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

### Step 2: Data Cleaning and Initial Exploration

* Use `df.info()` and `df.isnull().sum()` to check for missing values in each column.
* Remove the rows with missing values using `df.dropna(inplace = True)`.
* The `Year` column is a float but should be an integer. Covert it to int.
* Print the info again to confirm your changes.

In [ ]:
# Check for missing values
print("Missing values before cleaning:")
print(df.isnull().sum())

# Remove rows with any missing values
df.dropna(inplace=True)

# Convert 'Year' from float to integer
df['Year'] = df['Year'].astype(int)

# Check the info after cleaning
print("\nDataset info after cleaning:")
df.info()


Missing values before cleaning:
Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

Dataset info after cleaning:
<class 'pandas.core.frame.DataFrame'>
Index: 16291 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Rank          16291 non-null  int64  
 1   Name          16291 non-null  object 
 2   Platform      16291 non-null  object 
 3   Year          16291 non-null  int64  
 4   Genre         16291 non-null  object 
 5   Publisher     16291 non-null  object 
 6   NA_Sales      16291 non-null  float64
 7   EU_Sales      16291 non-null  float64
 8   JP_Sales      16291 non-null  float64
 9   Other_Sales   16291 non-null  float64
 10  Global_Sales  16291 non-null  float64
dtypes: float64(5), int64(2), object(4)
me

### Step 3: Answering Analytical Questions

**Question 1:  Which publisher has released the most games?**

***Hint:*** Use the .value_counts() method on the Publisher column.

**Question 2: Which genre sold the most copies in North America?**

***Hint:***  Use .groupby() on the Genre column, select the NA_Sales column, and calculate the .sum().

**Question 3: What is the standard deviation of global sales for the "Action" genre?**

***Hint:***  First, filter the DataFrame to get only "Action" games. Then, select the Global_Sales column and use the .std() method (which uses numpy underneath).

In [ ]:
# Question 1: Which publisher has released the most games?
most_prolific_publisher = df['Publisher'].value_counts().idxmax()
print(f"The publisher with the most released games is: {most_prolific_publisher}")

The publisher with the most released games is: Electronic Arts


In [ ]:
# Question 2: Which genre has the highest total sales in North America?
genre_sales_na = df.groupby('Genre')['NA_Sales'].sum().sort_values(ascending=False)
print("\nTotal sales in North America by genre:")
display(genre_sales_na)


Total sales in North America by genre:


Genre
Action          861.77
Sports          670.09
Shooter         575.16
Platform        445.99
Misc            396.92
Racing          356.93
Role-Playing    326.50
Fighting        220.74
Simulation      181.78
Puzzle          122.01
Adventure       101.93
Strategy         67.83
Name: NA_Sales, dtype: float64

In [ ]:
# Question 3: What is the standard deviation of global sales for Action games?
action_games = df[df['Genre'] == 'Action']
action_sales_std = action_games['Global_Sales'].std()
print(f"\nThe standard deviation of global sales for Action games is: {action_sales_std:.2f} million")


The standard deviation of global sales for Action games is: 1.17 million


## Bonus Challenge

Calculate the total global sales for each platform and determine which platform has the highest market share (percentage of total global sales).

In [ ]:
# Calculate total sales per platform
platform_sales = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False)
print("\nTotal global sales by platform:")
display(platform_sales)


Total global sales by platform:


Platform
PS2     1233.46
X360     969.60
PS3      949.35
Wii      909.81
DS       818.91
PS       727.39
GBA      305.62
PSP      291.71
PS4      278.10
PC       254.70
GB       254.42
XB       252.09
NES      251.07
3DS      246.27
N64      218.21
SNES     200.05
GC       197.14
XOne     141.06
2600      86.57
WiiU      81.86
PSV       61.60
SAT       33.59
GEN       28.36
DC        15.97
SCD        1.87
NG         1.44
WS         1.42
TG16       0.16
3DO        0.10
GG         0.04
PCFX       0.03
Name: Global_Sales, dtype: float64

In [ ]:
# Calculate total global sales for all games
total_global_sales = df['Global_Sales'].sum()

# Calculate market share
market_share = (platform_sales / total_global_sales) * 100
print("\nMarket share by platform (%):")
display(market_share)


Market share by platform (%):


Platform
PS2     13.997551
X360    11.003215
PS3     10.773414
Wii     10.324706
DS       9.293155
PS       8.254567
GBA      3.468237
PSP      3.310383
PS4      3.155934
PC       2.890387
GB       2.887209
XB       2.860768
NES      2.849193
3DS      2.794721
N64      2.476291
SNES     2.270207
GC       2.237184
XOne     1.600777
2600     0.982414
WiiU     0.928964
PSV      0.699049
SAT      0.381186
GEN      0.321835
DC       0.181231
SCD      0.021221
NG       0.016341
WS       0.016114
TG16     0.001816
3DO      0.001135
GG       0.000454
PCFX     0.000340
Name: Global_Sales, dtype: float64